---
- name: Verify that required variables are defined
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} | length > 0"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  loop:
    - fail2ban_admin_mail
    - fail2ban_jails

- name: Install fail2ban (and required nftables package)
  ansible.builtin.package:
    name:
      - fail2ban
      - nftables
    state: present
  become: true

- name: Copy template fail2ban jail local file
  ansible.builtin.template:
    src: jail.local.j2
    dest: "{{ fail2ban_dir }}/jail.local"
    owner: root
    mode: u=rw,g=r
    # validation not support by fail2ban
  become: true
  notify: restart fail2ban

- name: Copy nginx template files
  ansible.builtin.template:
    src: "filter.d/nginx-{{ item }}.conf"
    dest: "{{ fail2ban_dir }}/filter.d/nginx-{{ item }}.conf"
    owner: root
    mode: u=rw,g=r
    # validation not support by fail2ban
  become: true
  loop:
    - nohome
    - noproxy
    - noscript
  notify: restart fail2ban
